import { Experience } from '@/models/experience.model';

export const experiences: Experience[] = [
  {
    key: 'evolveIt',
    company: 'EvolveIT Solutions',
    link: 'https://www.evolveit.today/',
    imageUrl: '/images/companies/evolve-it.png',
    startedAt: new Date('2023-08-01'),
    skills: [
      'C#',
      '.NET',
      'ASP.NET',
      'SQL Server',
      'Redis',
      'Azure',
      'TypeScript',
      'Angular',
      'Microservices',
      'AI Integration',
    ],
  },
  {
    key: 'techSolutio',
    company: 'Tech Solutio',
    link: 'https://www.techsolutio.com',
    imageUrl: '/images/companies/tech-solutio.jpg',
    startedAt: new Date('2022-10-01'),
    endedAt: new Date('2023-08-01'),
    skills: [
      'Java',
      'Spring',
      'MySQL',
      'MongoDB',
      'Apache Kafka',
      'AWS',
      'Microservices',
      'Event-driven Architecture',
    ],
  },
  {
    key: 'fransciscoFarm',
    company: 'Fazenda São Franscisco',
    link: 'https://fazsaofrancisco.com/',
    imageUrl: '/images/companies/franscisco-farm.jpg',
    startedAt: new Date('2021-12-01'),
    endedAt: new Date('2022-10-01'),
    skills: [
      'Java',
      'Spring',
      'PostgreSQL',
      'Docker',
      'Angular',
      'Git',
      'Flutter',
      'QR Code',
      'Offline Sync',
      'Mobile Development',
    ],
  },
  {
    key: 'dantasEletro',
    company: 'Dantas Eletro',
    link: 'https://dantasbikes.com.br/',
    imageUrl: '/images/companies/dantas-eletro.jpg',
    startedAt: new Date('2020-09-01'),
    endedAt: new Date('2021-12-01'),
    skills: [
      'C#',
      '.NET',
      'ASP.NET',
      'PostgreSQL',
      'Docker',
      'React',
      'Redux',
      'TypeScript',
    ],
  },
  {
    key: 'capitalNerd',
    company: 'Capital Nerd',
    startedAt: new Date('2018-05-01'),
    endedAt: new Date('2020-09-01'),
    skills: [
      'C#',
      '.NET',
      'ASP.NET',
      'MySQL',
      'Hangfire',
      'Angular',
      'Git',
      'ERP',
    ],
  },
];
